# Generated by Django 2.2.17 on 2020-11-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='nbfvbvnvnbvnv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
