# Generated by Django 2.2.17 on 2020-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_nbfvbvnvnbvnv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='nbfvbvnvnbvnv',
            new_name='dfsfdfdgfdgf',
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
